const AnimalActionType = {
    CHANGE_SEARCH_FIELD: 'CHANGE_SEARCH_FIELD',
    FETCH_ANIMALS_START: 'FETCH_ANIMALS_START',
    FETCH_ANIMALS_SUCCESS: 'FETCH_ANIMALS_SUCCESS',
    FETCH_ANIMALS_FAILURE: 'FETCH_ANIMALS_FAILURE'
};


export default AnimalActionType;